# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

COPY microservices /app

# Install any needed packages specified in requirements.txt
COPY dockerfiles/aquarium-manager-service-requirements.txt /app/
RUN pip install --no-cache-dir -r aquarium-manager-service-requirements.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME AquariumManager

# Run aquarium-manager-service.py when the container launches
CMD ["python", "aquarium-manager-service.py"]