---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aquarium-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: aquarium-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "events", "configmaps", "secrets", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aquarium-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: aquarium-service-account
  namespace: default
roleRef:
  kind: Role
  name: aquarium-role
  apiGroup: rbac.authorization.k8s.io
