---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-simulator-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: event-simulator-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-simulator-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: event-simulator-account
  namespace: default
roleRef:
  kind: Role
  name: event-simulator-role
  apiGroup: rbac.authorization.k8s.io